version: "3.9"

services:
  db:
    build:
      context: ./database
    restart: always
    ports:
      - 5432:5432
    image: postgres:latest
    environment:
      POSTGRES_USER: sreality_user
      POSTGRES_PASSWORD: sreality_password
      POSTGRES_DB: sreality
      POSTGRES_HOST: localhost
    volumes:
      - ./database/data:/var/lib/postgresql/data
    networks:
      - main

  scraper:
    build:
      context: ./scraper
    depends_on:
      - db
    networks:
      - main

  server:
    build:
      context: ./server
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
      - scraper
    networks:
      - main

  adminer:
    image: adminer:4.8.1
    container_name: adminer
    restart: always
    ports:
      - 8000:8080

networks:
  main:

volumes:
  db-data:
